#!/usr/bin/env python

import sys
import os
import os.path


def main():
    if len(sys.argv) != 3:
        print("Usage: %s infile1 infile2" % sys.argv[0])
        sys.exit(2)
    file1 = sys.argv[1]
    file2 = sys.argv[2]
    path = os.path.dirname(os.path.realpath(__file__))
    os.system("%s/fasta-simplify %s | sort > __sorted1" % (path, file1)) 
    os.system("%s/fasta-simplify %s | sort > __sorted2" % (path, file2)) 
    ret = os.system("diff __sorted1 __sorted2")
    os.system("rm __sorted1 __sorted2")
    sys.exit(ret)
    

if __name__ == '__main__':
    main()
